name: hello_dart
version: 0.2.0
author: Marco Jakob <majakob@gmx.ch>
description: A visual and playful introduction to programming with Dart.
homepage: https://code.makery.ch/library/hello-dart/
documentation: https://github.com/marcojakob/hello-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  collection: ^1.14.11
  stagexl: ^1.4.0+2
  string_scanner: ^1.0.4
dev_dependencies:
  build_runner: ^1.1.1
  build_web_compilers: ^0.4.4+2